"""add tile features

Revision ID: 93960d8d9b85
Revises: 
Create Date: 2025-08-10 20:17:45.135625

"""
from typing import Sequence, Union

import sqlalchemy_utc
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93960d8d9b85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tile_features',
                    sa.Column('x', sa.BigInteger(), nullable=False),
                    sa.Column('y', sa.BigInteger(), nullable=False),
                    sa.Column('z', sa.BigInteger(), nullable=False),
                    sa.Column('version', sa.Text(), nullable=False),
                    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('x', 'y', 'z', 'version')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile_features')
    # ### end Alembic commands ###
